// Maps a template section's title onto the intelligence already gathered for an interview
// (the IC report body generated by finalizeInterview) so a board report can be assembled
// automatically. Unrecognised / custom section titles fall back to a clear "add manually" note
// rather than fabricating content. Matches are tried in order, most specific first, so a title
// like "Investment Committee Recommendation" doesn't accidentally match a looser "investment"
// pattern meant for something else.

export type ReportBlock =
  | { type: "paragraph"; text: string }
  | { type: "bullets"; heading?: string; items: string[] }
  | { type: "table"; rows: { label: string; value: string; redactable?: boolean }[] }
  | { type: "note"; text: string };

function bulletsBlock(heading: string, items?: string[] | null): ReportBlock | null {
  if (!items || !items.length) return null;
  return { type: "bullets", heading, items };
}

function fmtScore(s: { score: number; why: string } | undefined, label: string) {
  if (!s) return null;
  return { label, value: `${s.score}/100 — ${s.why}`, redactable: true };
}

type Matcher = { test: (t: string) => boolean; build: (r: any) => ReportBlock[] };

const MATCHERS: Matcher[] = [
  {
    test: (t) => t.includes("executive summary"),
    build: (r) => [{ type: "paragraph", text: r.executive_summary ?? "—" }],
  },
  {
    test: (t) => t.includes("founder summary"),
    build: (r) => [{ type: "paragraph", text: r.founder_summary ?? "—" }],
  },
  {
    test: (t) => t.includes("business summary"),
    build: (r) => [{ type: "paragraph", text: r.business_summary ?? "—" }],
  },
  {
    test: (t) => t.includes("deal summary"),
    build: (r) => [{ type: "paragraph", text: r.executive_summary ?? "—" }],
  },
  {
    test: (t) => t.includes("mess classification"),
    build: (r) => {
      const m = r.mess_classification;
      if (!m) return [{ type: "note", text: "Not yet classified." }];
      return [{ type: "table", rows: [
        { label: "Level", value: m.level ?? "—" },
        { label: "Reason", value: m.reason ?? "—" },
        { label: "Next step", value: m.next_step ?? "—" },
      ] }];
    },
  },
  {
    test: (t) => t.includes("investment committee recommendation") || t.includes("recommendation") || t.includes("investment consideration"),
    build: (r) => {
      const blocks: ReportBlock[] = [];
      if (r.recommendation?.verdict) blocks.push({ type: "table", rows: [{ label: "Verdict", value: r.recommendation.verdict }] });
      if (r.recommendation?.why) blocks.push({ type: "paragraph", text: r.recommendation.why });
      const conds = bulletsBlock("Conditions", r.recommendation?.conditions);
      if (conds) blocks.push(conds);
      return blocks.length ? blocks : [{ type: "note", text: "Not yet assessed." }];
    },
  },
  {
    test: (t) => t.includes("investment readiness") || t.includes("summary deal scoring") || t.includes("deal scoring"),
    build: (r) => {
      const ir = r.investment_readiness;
      if (!ir) return [{ type: "note", text: "Not yet scored." }];
      const rows = [
        { label: "Overall", value: `${ir.overall_score}/100`, redactable: true },
        fmtScore(ir.confidence, "Confidence"),
        fmtScore(ir.evidence_completeness, "Evidence completeness"),
        fmtScore(ir.founder_readiness, "Founder readiness"),
        fmtScore(ir.operational_maturity, "Operational maturity"),
        fmtScore(ir.financial_visibility, "Financial visibility"),
        fmtScore(ir.growth_readiness, "Growth readiness"),
      ].filter(Boolean) as { label: string; value: string; redactable?: boolean }[];
      return [{ type: "table", rows }];
    },
  },
  {
    test: (t) => t === "strengths" || (t.includes("strength") && !t.includes("weakness")),
    build: (r) => {
      const b = bulletsBlock("Strengths", r.strengths);
      return b ? [b] : [{ type: "note", text: "Not yet assessed." }];
    },
  },
  {
    test: (t) => t === "weaknesses" || t.includes("weakness"),
    build: (r) => {
      const b = bulletsBlock("Weaknesses", r.weaknesses);
      return b ? [b] : [{ type: "note", text: "Not yet assessed." }];
    },
  },
  {
    test: (t) => t.includes("value creation"),
    build: (r) => {
      const b = bulletsBlock("Value Creation Opportunities", r.value_creation_opportunities);
      return b ? [b] : [{ type: "note", text: "Not yet assessed." }];
    },
  },
  {
    test: (t) => t.includes("return pathway") || t === "outcomes",
    build: (r) => {
      const b = bulletsBlock("Return Pathways", r.return_pathways);
      return b ? [b] : [{ type: "note", text: "Not yet assessed." }];
    },
  },
  {
    test: (t) => t.includes("the raise") || t === "raise",
    build: (r) => [{ type: "table", rows: [
      { label: "Suggested deal structure", value: r.suggested_deal_structure ?? "—" },
      { label: "Equity range", value: r.equity_range ?? "—" },
    ] }],
  },
  {
    test: (t) => t.includes("suggested deal structure"),
    build: (r) => [{ type: "table", rows: [{ label: "Suggested deal structure", value: r.suggested_deal_structure ?? "—" }] }],
  },
  {
    test: (t) => t.includes("equity range"),
    build: (r) => [{ type: "table", rows: [{ label: "Equity range", value: r.equity_range ?? "—" }] }],
  },
  {
    test: (t) => t.includes("regulatory") || t.includes("reimbursement"),
    build: (r) => {
      const matches = (r.risk_assessment ?? []).filter((x: any) => /regulat|reimburs|complian|licen/i.test(`${x.category} ${x.reason}`));
      if (!matches.length) return [{ type: "note", text: "No regulatory or reimbursement-specific risks were identified in this round." }];
      return [{ type: "bullets", heading: "Regulatory Risks", items: matches.map((x: any) => `${x.category}: ${x.reason}`) }];
    },
  },
  {
    test: (t) => t.includes("risk assessment") || t.includes("risks to thesis") || t === "risks",
    build: (r) => {
      const blocks: ReportBlock[] = [];
      if (r.risk_assessment?.length) {
        blocks.push({ type: "table", rows: r.risk_assessment.map((x: any) => ({ label: `${x.category} (${x.rating})`, value: x.reason })) });
        const mitigations = r.risk_assessment.filter((x: any) => x.mitigation).map((x: any) => `${x.category}: ${x.mitigation}`);
        const m = bulletsBlock("Mitigations", mitigations);
        if (m) blocks.push(m);
      }
      return blocks.length ? blocks : [{ type: "note", text: "No risks flagged yet." }];
    },
  },
  {
    test: (t) => t.includes("founder") || t.includes("team"),
    build: (r) => [{ type: "paragraph", text: r.founder_summary ?? "—" }],
  },
  {
    test: (t) => t.includes("market") || t.includes("competition"),
    build: (r) => {
      const blocks = [bulletsBlock("Strengths", r.strengths), bulletsBlock("Weaknesses", r.weaknesses)].filter(Boolean) as ReportBlock[];
      return blocks.length ? blocks : [{ type: "note", text: "Not yet assessed." }];
    },
  },
  {
    test: (t) => t.includes("product"),
    build: (r) => {
      const blocks: ReportBlock[] = [{ type: "paragraph", text: r.business_summary ?? "—" }];
      const opps = bulletsBlock("Opportunities", r.value_creation_opportunities);
      if (opps) blocks.push(opps);
      return blocks;
    },
  },
  {
    test: (t) => t.includes("business model"),
    build: (r) => {
      const blocks: ReportBlock[] = [];
      if (r.mess_classification?.reason) blocks.push({ type: "paragraph", text: r.mess_classification.reason });
      const ws = bulletsBlock("Priority Workstreams", r.priority_workstreams);
      if (ws) blocks.push(ws);
      return blocks.length ? blocks : [{ type: "note", text: "Not yet assessed." }];
    },
  },
  {
    test: (t) => t.includes("traction"),
    build: (r) => {
      const b = bulletsBlock("Strengths", r.strengths);
      return b ? [b] : [{ type: "note", text: "Not yet assessed." }];
    },
  },
  {
    test: (t) => t.includes("forward plan") || t.includes("100-day") || t.includes("100 day") || t.includes("hundred"),
    build: (r) => {
      const plan = r.hundred_day_plan;
      if (!plan?.length) return [{ type: "note", text: "No 100-day plan generated yet." }];
      return [{ type: "table", rows: plan.map((p: any) => ({ label: p.day_range, value: `${p.workstream} — ${p.outcome}` })) }];
    },
  },
  {
    test: (t) => t.includes("investment thesis"),
    build: (r) => {
      const blocks = [bulletsBlock("Value Creation Opportunities", r.value_creation_opportunities), bulletsBlock("Return Pathways", r.return_pathways)].filter(Boolean) as ReportBlock[];
      return blocks.length ? blocks : [{ type: "note", text: "Not yet assessed." }];
    },
  },
  {
    test: (t) => t.includes("impact thesis") || t.includes("impact framework") || t.includes("impact assessment"),
    build: () => [{ type: "note", text: "Not yet assessed for this opportunity — add manually." }],
  },
  {
    test: (t) => t.includes("outstanding question"),
    build: (r) => {
      const b = bulletsBlock("Outstanding Questions", r.outstanding_questions);
      return b ? [b] : [{ type: "note", text: "None outstanding." }];
    },
  },
  {
    test: (t) => t.includes("evidence required"),
    build: (r) => {
      const b = bulletsBlock("Evidence Required", r.evidence_required);
      return b ? [b] : [{ type: "note", text: "None outstanding." }];
    },
  },
  {
    test: (t) => t.includes("recommended next step"),
    build: (r) => {
      const b = bulletsBlock("Recommended Next Steps", r.recommended_next_steps);
      return b ? [b] : [{ type: "note", text: "None yet." }];
    },
  },
  {
    test: (t) => t.includes("suggested specialist"),
    build: (r) => {
      const b = bulletsBlock("Suggested Specialists", r.suggested_specialists);
      return b ? [b] : [{ type: "note", text: "None suggested yet." }];
    },
  },
  {
    test: (t) => t.includes("priority workstream"),
    build: (r) => {
      const b = bulletsBlock("Priority Workstreams", r.priority_workstreams);
      return b ? [b] : [{ type: "note", text: "None yet." }];
    },
  },
  {
    test: (t) => t.includes("due diligence"),
    build: (r) => {
      const blocks = [
        bulletsBlock("Outstanding Questions", r.outstanding_questions),
        bulletsBlock("Evidence Required", r.evidence_required),
        bulletsBlock("Recommended Next Steps", r.recommended_next_steps),
      ].filter(Boolean) as ReportBlock[];
      return blocks.length ? blocks : [{ type: "note", text: "Not yet assessed." }];
    },
  },
  {
    test: (t) => t.includes("deep dive") || t.includes("company overview"),
    build: (r) => [{ type: "paragraph", text: r.business_summary ?? "—" }],
  },
  {
    test: (t) => t.includes("the problem"),
    build: (r) => [{ type: "note", text: "Not captured as a distinct field yet — see Company Overview / Business Summary for context." }],
  },
  {
    test: (t) => t.includes("the solution"),
    build: (r) => [{ type: "paragraph", text: r.business_summary ?? "—" }],
  },
  {
    test: (t) => t.includes("why now"),
    build: () => [{ type: "note", text: "Not captured as a distinct field yet — add manually." }],
  },
];

export function buildSectionBlocks(title: string, r: any): ReportBlock[] {
  const t = title.trim().toLowerCase();
  if (!r) return [{ type: "note", text: "No IC memo has been generated for this interview yet." }];
  const match = MATCHERS.find((m) => m.test(t));
  return match ? match.build(r) : [{ type: "note", text: "Content for this section hasn't been mapped yet — add manually." }];
}
