/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as FoundersRouteImport } from './routes/founders'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as DdEngineRouteImport } from './routes/dd-engine'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities.index'
import { Route as InterviewsIndexRouteImport } from './routes/interviews.index'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as OpportunitiesIdRouteImport } from './routes/opportunities.$id'
import { Route as InterviewsIdRouteImport } from './routes/interviews.$id'
import { Route as FoundersIdRouteImport } from './routes/founders.$id'
import { Route as CompaniesIdRouteImport } from './routes/companies.$id'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as DdEngineWizardOppIdRouteImport } from './routes/dd-engine.wizard.$oppId'

const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundersRoute = FoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const DdEngineRoute = DdEngineRouteImport.update({
  id: '/dd-engine',
  path: '/dd-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsIndexRoute = InterviewsIndexRouteImport.update({
  id: '/interviews/',
  path: '/interviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIdRoute = OpportunitiesIdRouteImport.update({
  id: '/opportunities/$id',
  path: '/opportunities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsIdRoute = InterviewsIdRouteImport.update({
  id: '/interviews/$id',
  path: '/interviews/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundersIdRoute = FoundersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FoundersRoute,
} as any)
const CompaniesIdRoute = CompaniesIdRouteImport.update({
  id: '/companies/$id',
  path: '/companies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DdEngineWizardOppIdRoute = DdEngineWizardOppIdRouteImport.update({
  id: '/wizard/$oppId',
  path: '/wizard/$oppId',
  getParentRoute: () => DdEngineRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/dd-engine': typeof DdEngineRouteWithChildren
  '/deals': typeof DealsRoute
  '/ecosystem': typeof EcosystemRoute
  '/events': typeof EventsRoute
  '/founders': typeof FoundersRouteWithChildren
  '/vendors': typeof VendorsRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/founders/$id': typeof FoundersIdRoute
  '/interviews/$id': typeof InterviewsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/companies/': typeof CompaniesIndexRoute
  '/interviews/': typeof InterviewsIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/dd-engine/wizard/$oppId': typeof DdEngineWizardOppIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/dd-engine': typeof DdEngineRouteWithChildren
  '/deals': typeof DealsRoute
  '/ecosystem': typeof EcosystemRoute
  '/events': typeof EventsRoute
  '/founders': typeof FoundersRouteWithChildren
  '/vendors': typeof VendorsRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/founders/$id': typeof FoundersIdRoute
  '/interviews/$id': typeof InterviewsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/companies': typeof CompaniesIndexRoute
  '/interviews': typeof InterviewsIndexRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/dd-engine/wizard/$oppId': typeof DdEngineWizardOppIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/dd-engine': typeof DdEngineRouteWithChildren
  '/deals': typeof DealsRoute
  '/ecosystem': typeof EcosystemRoute
  '/events': typeof EventsRoute
  '/founders': typeof FoundersRouteWithChildren
  '/vendors': typeof VendorsRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/founders/$id': typeof FoundersIdRoute
  '/interviews/$id': typeof InterviewsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/companies/': typeof CompaniesIndexRoute
  '/interviews/': typeof InterviewsIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/dd-engine/wizard/$oppId': typeof DdEngineWizardOppIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/auth'
    | '/dd-engine'
    | '/deals'
    | '/ecosystem'
    | '/events'
    | '/founders'
    | '/vendors'
    | '/api/transcribe'
    | '/companies/$id'
    | '/founders/$id'
    | '/interviews/$id'
    | '/opportunities/$id'
    | '/companies/'
    | '/interviews/'
    | '/opportunities/'
    | '/dd-engine/wizard/$oppId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/auth'
    | '/dd-engine'
    | '/deals'
    | '/ecosystem'
    | '/events'
    | '/founders'
    | '/vendors'
    | '/api/transcribe'
    | '/companies/$id'
    | '/founders/$id'
    | '/interviews/$id'
    | '/opportunities/$id'
    | '/companies'
    | '/interviews'
    | '/opportunities'
    | '/dd-engine/wizard/$oppId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/auth'
    | '/dd-engine'
    | '/deals'
    | '/ecosystem'
    | '/events'
    | '/founders'
    | '/vendors'
    | '/api/transcribe'
    | '/companies/$id'
    | '/founders/$id'
    | '/interviews/$id'
    | '/opportunities/$id'
    | '/companies/'
    | '/interviews/'
    | '/opportunities/'
    | '/dd-engine/wizard/$oppId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  DdEngineRoute: typeof DdEngineRouteWithChildren
  DealsRoute: typeof DealsRoute
  EcosystemRoute: typeof EcosystemRoute
  EventsRoute: typeof EventsRoute
  FoundersRoute: typeof FoundersRouteWithChildren
  VendorsRoute: typeof VendorsRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  CompaniesIdRoute: typeof CompaniesIdRoute
  InterviewsIdRoute: typeof InterviewsIdRoute
  OpportunitiesIdRoute: typeof OpportunitiesIdRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  InterviewsIndexRoute: typeof InterviewsIndexRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founders': {
      id: '/founders'
      path: '/founders'
      fullPath: '/founders'
      preLoaderRoute: typeof FoundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dd-engine': {
      id: '/dd-engine'
      path: '/dd-engine'
      fullPath: '/dd-engine'
      preLoaderRoute: typeof DdEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews/': {
      id: '/interviews/'
      path: '/interviews'
      fullPath: '/interviews/'
      preLoaderRoute: typeof InterviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$id': {
      id: '/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof OpportunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews/$id': {
      id: '/interviews/$id'
      path: '/interviews/$id'
      fullPath: '/interviews/$id'
      preLoaderRoute: typeof InterviewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founders/$id': {
      id: '/founders/$id'
      path: '/$id'
      fullPath: '/founders/$id'
      preLoaderRoute: typeof FoundersIdRouteImport
      parentRoute: typeof FoundersRoute
    }
    '/companies/$id': {
      id: '/companies/$id'
      path: '/companies/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof CompaniesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dd-engine/wizard/$oppId': {
      id: '/dd-engine/wizard/$oppId'
      path: '/wizard/$oppId'
      fullPath: '/dd-engine/wizard/$oppId'
      preLoaderRoute: typeof DdEngineWizardOppIdRouteImport
      parentRoute: typeof DdEngineRoute
    }
  }
}

interface DdEngineRouteChildren {
  DdEngineWizardOppIdRoute: typeof DdEngineWizardOppIdRoute
}

const DdEngineRouteChildren: DdEngineRouteChildren = {
  DdEngineWizardOppIdRoute: DdEngineWizardOppIdRoute,
}

const DdEngineRouteWithChildren = DdEngineRoute._addFileChildren(
  DdEngineRouteChildren,
)

interface FoundersRouteChildren {
  FoundersIdRoute: typeof FoundersIdRoute
}

const FoundersRouteChildren: FoundersRouteChildren = {
  FoundersIdRoute: FoundersIdRoute,
}

const FoundersRouteWithChildren = FoundersRoute._addFileChildren(
  FoundersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  DdEngineRoute: DdEngineRouteWithChildren,
  DealsRoute: DealsRoute,
  EcosystemRoute: EcosystemRoute,
  EventsRoute: EventsRoute,
  FoundersRoute: FoundersRouteWithChildren,
  VendorsRoute: VendorsRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  CompaniesIdRoute: CompaniesIdRoute,
  InterviewsIdRoute: InterviewsIdRoute,
  OpportunitiesIdRoute: OpportunitiesIdRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  InterviewsIndexRoute: InterviewsIndexRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
