/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as EventsOldRouteImport } from './routes/events-old'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as DdEngineRouteImport } from './routes/dd-engine'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities.index'
import { Route as InterviewsIndexRouteImport } from './routes/interviews.index'
import { Route as ContactsIndexRouteImport } from './routes/contacts.index'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as OpportunitiesIdRouteImport } from './routes/opportunities.$id'
import { Route as InterviewsIdRouteImport } from './routes/interviews.$id'
import { Route as ContactsIdRouteImport } from './routes/contacts.$id'
import { Route as CompaniesIdRouteImport } from './routes/companies.$id'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as AdminDdFrameworkRouteImport } from './routes/admin.dd-framework'
import { Route as AdminAccountsRouteImport } from './routes/admin.accounts'
import { Route as OpportunitiesIdSynopsisRouteImport } from './routes/opportunities_.$id.synopsis'
import { Route as DdInterviewOpportunityIdRoundRouteImport } from './routes/dd-interview.$opportunityId.$round'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google.callback'
import { Route as ApiCronSyncGoogleCalendarsRouteImport } from './routes/api/cron.sync-google-calendars'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsOldRoute = EventsOldRouteImport.update({
  id: '/events-old',
  path: '/events-old',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const DdEngineRoute = DdEngineRouteImport.update({
  id: '/dd-engine',
  path: '/dd-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsIndexRoute = InterviewsIndexRouteImport.update({
  id: '/interviews/',
  path: '/interviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIdRoute = OpportunitiesIdRouteImport.update({
  id: '/opportunities/$id',
  path: '/opportunities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsIdRoute = InterviewsIdRouteImport.update({
  id: '/interviews/$id',
  path: '/interviews/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIdRoute = ContactsIdRouteImport.update({
  id: '/contacts/$id',
  path: '/contacts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIdRoute = CompaniesIdRouteImport.update({
  id: '/companies/$id',
  path: '/companies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDdFrameworkRoute = AdminDdFrameworkRouteImport.update({
  id: '/admin/dd-framework',
  path: '/admin/dd-framework',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/admin/accounts',
  path: '/admin/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIdSynopsisRoute = OpportunitiesIdSynopsisRouteImport.update({
  id: '/opportunities_/$id/synopsis',
  path: '/opportunities/$id/synopsis',
  getParentRoute: () => rootRouteImport,
} as any)
const DdInterviewOpportunityIdRoundRoute =
  DdInterviewOpportunityIdRoundRouteImport.update({
    id: '/dd-interview/$opportunityId/$round',
    path: '/dd-interview/$opportunityId/$round',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/google/callback',
  path: '/google/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiCronSyncGoogleCalendarsRoute =
  ApiCronSyncGoogleCalendarsRouteImport.update({
    id: '/api/cron/sync-google-calendars',
    path: '/api/cron/sync-google-calendars',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/dd-engine': typeof DdEngineRoute
  '/deals': typeof DealsRoute
  '/events': typeof EventsRoute
  '/events-old': typeof EventsOldRoute
  '/tasks': typeof TasksRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/dd-framework': typeof AdminDdFrameworkRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/book/$slug': typeof BookSlugRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/interviews/$id': typeof InterviewsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/companies/': typeof CompaniesIndexRoute
  '/contacts/': typeof ContactsIndexRoute
  '/interviews/': typeof InterviewsIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/api/cron/sync-google-calendars': typeof ApiCronSyncGoogleCalendarsRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/dd-interview/$opportunityId/$round': typeof DdInterviewOpportunityIdRoundRoute
  '/opportunities/$id/synopsis': typeof OpportunitiesIdSynopsisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/dd-engine': typeof DdEngineRoute
  '/deals': typeof DealsRoute
  '/events': typeof EventsRoute
  '/events-old': typeof EventsOldRoute
  '/tasks': typeof TasksRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/dd-framework': typeof AdminDdFrameworkRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/book/$slug': typeof BookSlugRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/interviews/$id': typeof InterviewsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/companies': typeof CompaniesIndexRoute
  '/contacts': typeof ContactsIndexRoute
  '/interviews': typeof InterviewsIndexRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/api/cron/sync-google-calendars': typeof ApiCronSyncGoogleCalendarsRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/dd-interview/$opportunityId/$round': typeof DdInterviewOpportunityIdRoundRoute
  '/opportunities/$id/synopsis': typeof OpportunitiesIdSynopsisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/dd-engine': typeof DdEngineRoute
  '/deals': typeof DealsRoute
  '/events': typeof EventsRoute
  '/events-old': typeof EventsOldRoute
  '/tasks': typeof TasksRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/dd-framework': typeof AdminDdFrameworkRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/book/$slug': typeof BookSlugRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/interviews/$id': typeof InterviewsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/companies/': typeof CompaniesIndexRoute
  '/contacts/': typeof ContactsIndexRoute
  '/interviews/': typeof InterviewsIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/api/cron/sync-google-calendars': typeof ApiCronSyncGoogleCalendarsRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/dd-interview/$opportunityId/$round': typeof DdInterviewOpportunityIdRoundRoute
  '/opportunities_/$id/synopsis': typeof OpportunitiesIdSynopsisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/dd-engine'
    | '/deals'
    | '/events'
    | '/events-old'
    | '/tasks'
    | '/admin/accounts'
    | '/admin/dd-framework'
    | '/api/transcribe'
    | '/book/$slug'
    | '/companies/$id'
    | '/contacts/$id'
    | '/interviews/$id'
    | '/opportunities/$id'
    | '/companies/'
    | '/contacts/'
    | '/interviews/'
    | '/opportunities/'
    | '/api/cron/sync-google-calendars'
    | '/auth/google/callback'
    | '/dd-interview/$opportunityId/$round'
    | '/opportunities/$id/synopsis'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/dd-engine'
    | '/deals'
    | '/events'
    | '/events-old'
    | '/tasks'
    | '/admin/accounts'
    | '/admin/dd-framework'
    | '/api/transcribe'
    | '/book/$slug'
    | '/companies/$id'
    | '/contacts/$id'
    | '/interviews/$id'
    | '/opportunities/$id'
    | '/companies'
    | '/contacts'
    | '/interviews'
    | '/opportunities'
    | '/api/cron/sync-google-calendars'
    | '/auth/google/callback'
    | '/dd-interview/$opportunityId/$round'
    | '/opportunities/$id/synopsis'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/calendar'
    | '/dd-engine'
    | '/deals'
    | '/events'
    | '/events-old'
    | '/tasks'
    | '/admin/accounts'
    | '/admin/dd-framework'
    | '/api/transcribe'
    | '/book/$slug'
    | '/companies/$id'
    | '/contacts/$id'
    | '/interviews/$id'
    | '/opportunities/$id'
    | '/companies/'
    | '/contacts/'
    | '/interviews/'
    | '/opportunities/'
    | '/api/cron/sync-google-calendars'
    | '/auth/google/callback'
    | '/dd-interview/$opportunityId/$round'
    | '/opportunities_/$id/synopsis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  DdEngineRoute: typeof DdEngineRoute
  DealsRoute: typeof DealsRoute
  EventsRoute: typeof EventsRoute
  EventsOldRoute: typeof EventsOldRoute
  TasksRoute: typeof TasksRoute
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminDdFrameworkRoute: typeof AdminDdFrameworkRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  BookSlugRoute: typeof BookSlugRoute
  CompaniesIdRoute: typeof CompaniesIdRoute
  ContactsIdRoute: typeof ContactsIdRoute
  InterviewsIdRoute: typeof InterviewsIdRoute
  OpportunitiesIdRoute: typeof OpportunitiesIdRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
  InterviewsIndexRoute: typeof InterviewsIndexRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
  ApiCronSyncGoogleCalendarsRoute: typeof ApiCronSyncGoogleCalendarsRoute
  DdInterviewOpportunityIdRoundRoute: typeof DdInterviewOpportunityIdRoundRoute
  OpportunitiesIdSynopsisRoute: typeof OpportunitiesIdSynopsisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events-old': {
      id: '/events-old'
      path: '/events-old'
      fullPath: '/events-old'
      preLoaderRoute: typeof EventsOldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dd-engine': {
      id: '/dd-engine'
      path: '/dd-engine'
      fullPath: '/dd-engine'
      preLoaderRoute: typeof DdEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews/': {
      id: '/interviews/'
      path: '/interviews'
      fullPath: '/interviews/'
      preLoaderRoute: typeof InterviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$id': {
      id: '/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof OpportunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews/$id': {
      id: '/interviews/$id'
      path: '/interviews/$id'
      fullPath: '/interviews/$id'
      preLoaderRoute: typeof InterviewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/$id': {
      id: '/contacts/$id'
      path: '/contacts/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof ContactsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$id': {
      id: '/companies/$id'
      path: '/companies/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof CompaniesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dd-framework': {
      id: '/admin/dd-framework'
      path: '/admin/dd-framework'
      fullPath: '/admin/dd-framework'
      preLoaderRoute: typeof AdminDdFrameworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/admin/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities_/$id/synopsis': {
      id: '/opportunities_/$id/synopsis'
      path: '/opportunities/$id/synopsis'
      fullPath: '/opportunities/$id/synopsis'
      preLoaderRoute: typeof OpportunitiesIdSynopsisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dd-interview/$opportunityId/$round': {
      id: '/dd-interview/$opportunityId/$round'
      path: '/dd-interview/$opportunityId/$round'
      fullPath: '/dd-interview/$opportunityId/$round'
      preLoaderRoute: typeof DdInterviewOpportunityIdRoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/cron/sync-google-calendars': {
      id: '/api/cron/sync-google-calendars'
      path: '/api/cron/sync-google-calendars'
      fullPath: '/api/cron/sync-google-calendars'
      preLoaderRoute: typeof ApiCronSyncGoogleCalendarsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  CalendarRoute: CalendarRoute,
  DdEngineRoute: DdEngineRoute,
  DealsRoute: DealsRoute,
  EventsRoute: EventsRoute,
  EventsOldRoute: EventsOldRoute,
  TasksRoute: TasksRoute,
  AdminAccountsRoute: AdminAccountsRoute,
  AdminDdFrameworkRoute: AdminDdFrameworkRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  BookSlugRoute: BookSlugRoute,
  CompaniesIdRoute: CompaniesIdRoute,
  ContactsIdRoute: ContactsIdRoute,
  InterviewsIdRoute: InterviewsIdRoute,
  OpportunitiesIdRoute: OpportunitiesIdRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  ContactsIndexRoute: ContactsIndexRoute,
  InterviewsIndexRoute: InterviewsIndexRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
  ApiCronSyncGoogleCalendarsRoute: ApiCronSyncGoogleCalendarsRoute,
  DdInterviewOpportunityIdRoundRoute: DdInterviewOpportunityIdRoundRoute,
  OpportunitiesIdSynopsisRoute: OpportunitiesIdSynopsisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
