/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FoundersRouteImport } from './routes/founders'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InterviewsIndexRouteImport } from './routes/interviews.index'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'

const FoundersRoute = FoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsIndexRoute = InterviewsIndexRouteImport.update({
  id: '/interviews/',
  path: '/interviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/contacts': typeof ContactsRoute
  '/deals': typeof DealsRoute
  '/ecosystem': typeof EcosystemRoute
  '/events': typeof EventsRoute
  '/founders': typeof FoundersRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/interviews/': typeof InterviewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/contacts': typeof ContactsRoute
  '/deals': typeof DealsRoute
  '/ecosystem': typeof EcosystemRoute
  '/events': typeof EventsRoute
  '/founders': typeof FoundersRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/interviews': typeof InterviewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/contacts': typeof ContactsRoute
  '/deals': typeof DealsRoute
  '/ecosystem': typeof EcosystemRoute
  '/events': typeof EventsRoute
  '/founders': typeof FoundersRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/interviews/': typeof InterviewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/auth'
    | '/contacts'
    | '/deals'
    | '/ecosystem'
    | '/events'
    | '/founders'
    | '/api/transcribe'
    | '/interviews/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/auth'
    | '/contacts'
    | '/deals'
    | '/ecosystem'
    | '/events'
    | '/founders'
    | '/api/transcribe'
    | '/interviews'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/auth'
    | '/contacts'
    | '/deals'
    | '/ecosystem'
    | '/events'
    | '/founders'
    | '/api/transcribe'
    | '/interviews/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  ContactsRoute: typeof ContactsRoute
  DealsRoute: typeof DealsRoute
  EcosystemRoute: typeof EcosystemRoute
  EventsRoute: typeof EventsRoute
  FoundersRoute: typeof FoundersRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  InterviewsIndexRoute: typeof InterviewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/founders': {
      id: '/founders'
      path: '/founders'
      fullPath: '/founders'
      preLoaderRoute: typeof FoundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews/': {
      id: '/interviews/'
      path: '/interviews'
      fullPath: '/interviews/'
      preLoaderRoute: typeof InterviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  ContactsRoute: ContactsRoute,
  DealsRoute: DealsRoute,
  EcosystemRoute: EcosystemRoute,
  EventsRoute: EventsRoute,
  FoundersRoute: FoundersRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  InterviewsIndexRoute: InterviewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
