-- Admin > Templates: reusable IC-report layouts. Each template is an ordered list of
-- sections (drag-and-drop reorderable, with up to 3 heading levels for
-- section / subsection / sub-subsection) plus optional cover colours and a sample
-- attachment kept as a visual reference for that brand's styling.

create table if not exists public.report_templates (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  sample_attachment_url text,
  sample_attachment_name text,
  cover_bg text,
  cover_fg text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.report_template_sections (
  id uuid primary key default gen_random_uuid(),
  template_id uuid not null references public.report_templates(id) on delete cascade,
  title text not null,
  level smallint not null default 1,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.report_templates enable row level security;
alter table public.report_template_sections enable row level security;

drop policy if exists "report_templates team all" on public.report_templates;
create policy "report_templates team all" on public.report_templates
  for all to authenticated using (true) with check (true);

drop policy if exists "report_template_sections team all" on public.report_template_sections;
create policy "report_template_sections team all" on public.report_template_sections
  for all to authenticated using (true) with check (true);

-- Sample-attachment reference files (logos, past board decks, brand style sheets) --
-- public bucket since these are internal branding references, not confidential documents.
insert into storage.buckets (id, name, public)
values ('report-template-samples', 'report-template-samples', true)
on conflict (id) do nothing;

drop policy if exists "report_template_samples team all" on storage.objects;
create policy "report_template_samples team all" on storage.objects
  for all to authenticated
  using (bucket_id = 'report-template-samples')
  with check (bucket_id = 'report-template-samples');

-- Seed three templates: the generic TOC layout, the original IC-memo field layout
-- already built into the app, and First Serve Ventures' own layout (modelled on the
-- sample memo screenshots provided -- dark navy cover, nested Deep Dive/Company
-- Overview/Problem-Solution-Why Now, and an Impact Thesis with FSV-specific scoring).
do $$
declare
  alice_lane_id uuid;
  ic_memo_id uuid;
  first_serve_id uuid;
  toc_sections text[] := array[
    'Deal Summary', 'Investment Consideration', 'The Raise', 'Summary Deal Scoring',
    'Deep Dive: Company Overview', 'Regulatory and Reimbursement', 'Founders and the Team',
    'The Market and Competition', 'Product Overview', 'Business Model', 'Traction',
    'Forward Plan', 'Investment Thesis', 'Outcomes', 'Risks to Thesis', 'Impact Thesis',
    'Due Diligence'
  ];
  ic_memo_sections text[] := array[
    'Investment Committee Recommendation', 'Executive Summary', 'Founder Summary', 'Business Summary',
    'Mess Classification', 'Investment Readiness', 'Strengths', 'Weaknesses',
    'Value Creation Opportunities', 'Return Pathways', 'Risk Assessment', 'Outstanding Questions',
    'Evidence Required', 'Recommended Next Steps', '100-Day Plan', 'Suggested Deal Structure',
    'Equity Range', 'Suggested Specialists', 'Priority Workstreams'
  ];
  i integer;
begin
  insert into public.report_templates (name, description)
  values ('Alice Lane Template', 'Default Alice Lane Capital board-ready IC report layout.')
  returning id into alice_lane_id;

  insert into public.report_templates (name, description)
  values ('Alice Lane — Original IC Memo', 'The original IC memo field layout generated by the interview workspace, in its native order.')
  returning id into ic_memo_id;

  insert into public.report_templates (name, description, cover_bg, cover_fg)
  values ('First Serve Ventures Template', 'First Serve Ventures board-ready IC report layout, modelled on their own memo format.', '#33335c', '#ffffff')
  returning id into first_serve_id;

  for i in 1..array_length(toc_sections, 1) loop
    insert into public.report_template_sections (template_id, title, level, sort_order) values (alice_lane_id, toc_sections[i], 1, i);
  end loop;

  for i in 1..array_length(ic_memo_sections, 1) loop
    insert into public.report_template_sections (template_id, title, level, sort_order) values (ic_memo_id, ic_memo_sections[i], 1, i);
  end loop;

  -- First Serve Ventures: nested structure matching the sample memo (level 1 = new page,
  -- level 2/3 = subsections stacked on that same page).
  insert into public.report_template_sections (template_id, title, level, sort_order) values
    (first_serve_id, 'Deal Summary', 1, 1),
    (first_serve_id, 'Investment Consideration', 2, 2),
    (first_serve_id, 'The Raise', 2, 3),
    (first_serve_id, 'Deep Dive', 1, 4),
    (first_serve_id, 'Company Overview', 2, 5),
    (first_serve_id, 'The Problem', 3, 6),
    (first_serve_id, 'The Solution', 3, 7),
    (first_serve_id, 'Why Now', 3, 8),
    (first_serve_id, 'Founders and the Team', 1, 9),
    (first_serve_id, 'The Market and Competition', 1, 10),
    (first_serve_id, 'Product Overview', 1, 11),
    (first_serve_id, 'Business Model', 1, 12),
    (first_serve_id, 'Traction', 1, 13),
    (first_serve_id, 'Forward Plan', 1, 14),
    (first_serve_id, 'Investment Thesis', 1, 15),
    (first_serve_id, 'Outcomes', 1, 16),
    (first_serve_id, 'Risks to Thesis', 1, 17),
    (first_serve_id, 'Impact Thesis', 1, 18),
    (first_serve_id, 'FSV Impact Framework', 2, 19),
    (first_serve_id, 'FSV Impact Assessment Score', 2, 20),
    (first_serve_id, 'Due Diligence', 1, 21);
end $$;
